ALTER TABLE profiles ADD COLUMN linkedin TEXT NOT NULL DEFAULT '';
ALTER TABLE profiles ADD COLUMN x TEXT NOT NULL DEFAULT '';
ALTER TABLE profiles ADD COLUMN github TEXT NOT NULL DEFAULT '';
ALTER TABLE profiles ADD COLUMN other_social TEXT NOT NULL DEFAULT '';
